// Generated by delombok at Tue Apr 07 10:25:18 IST 2026
package com.vit.timetable.model;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "rooms")
public class Room {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String roomNumber;
    private int capacity;
    // Lab rooms vs lecture halls
    private boolean isLab;

    public Long getId() {
        return this.id;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class RoomBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String roomNumber;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int capacity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean isLab;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        RoomBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Room.RoomBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Room.RoomBuilder roomNumber(final String roomNumber) {
            this.roomNumber = roomNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Room.RoomBuilder capacity(final int capacity) {
            this.capacity = capacity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Room.RoomBuilder isLab(final boolean isLab) {
            this.isLab = isLab;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Room build() {
            return new Room(this.id, this.roomNumber, this.capacity, this.isLab);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Room.RoomBuilder(id=" + this.id + ", roomNumber=" + this.roomNumber + ", capacity=" + this.capacity + ", isLab=" + this.isLab + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Room.RoomBuilder builder() {
        return new Room.RoomBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRoomNumber() {
        return this.roomNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCapacity() {
        return this.capacity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isLab() {
        return this.isLab;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRoomNumber(final String roomNumber) {
        this.roomNumber = roomNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCapacity(final int capacity) {
        this.capacity = capacity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLab(final boolean isLab) {
        this.isLab = isLab;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Room)) return false;
        final Room other = (Room) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getCapacity() != other.getCapacity()) return false;
        if (this.isLab() != other.isLab()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$roomNumber = this.getRoomNumber();
        final java.lang.Object other$roomNumber = other.getRoomNumber();
        if (this$roomNumber == null ? other$roomNumber != null : !this$roomNumber.equals(other$roomNumber)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Room;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getCapacity();
        result = result * PRIME + (this.isLab() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $roomNumber = this.getRoomNumber();
        result = result * PRIME + ($roomNumber == null ? 43 : $roomNumber.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Room(id=" + this.getId() + ", roomNumber=" + this.getRoomNumber() + ", capacity=" + this.getCapacity() + ", isLab=" + this.isLab() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Room() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Room(final Long id, final String roomNumber, final int capacity, final boolean isLab) {
        this.id = id;
        this.roomNumber = roomNumber;
        this.capacity = capacity;
        this.isLab = isLab;
    }
}
