// Generated by delombok at Tue Apr 07 10:25:19 IST 2026
package com.vit.timetable.model;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "subjects")
public class Subject {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    private String code;
    // How many lectures per week
    private int hoursPerWeek;
    // Is this a lab session? (labs are 2hr blocks)
    private boolean isLab;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getHoursPerWeek() {
        return this.hoursPerWeek;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class SubjectBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String code;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int hoursPerWeek;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean isLab;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        SubjectBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Subject.SubjectBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Subject.SubjectBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Subject.SubjectBuilder code(final String code) {
            this.code = code;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Subject.SubjectBuilder hoursPerWeek(final int hoursPerWeek) {
            this.hoursPerWeek = hoursPerWeek;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Subject.SubjectBuilder isLab(final boolean isLab) {
            this.isLab = isLab;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Subject build() {
            return new Subject(this.id, this.name, this.code, this.hoursPerWeek, this.isLab);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Subject.SubjectBuilder(id=" + this.id + ", name=" + this.name + ", code=" + this.code + ", hoursPerWeek=" + this.hoursPerWeek + ", isLab=" + this.isLab + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Subject.SubjectBuilder builder() {
        return new Subject.SubjectBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isLab() {
        return this.isLab;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCode(final String code) {
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHoursPerWeek(final int hoursPerWeek) {
        this.hoursPerWeek = hoursPerWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLab(final boolean isLab) {
        this.isLab = isLab;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Subject)) return false;
        final Subject other = (Subject) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getHoursPerWeek() != other.getHoursPerWeek()) return false;
        if (this.isLab() != other.isLab()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$code = this.getCode();
        final java.lang.Object other$code = other.getCode();
        if (this$code == null ? other$code != null : !this$code.equals(other$code)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Subject;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getHoursPerWeek();
        result = result * PRIME + (this.isLab() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $code = this.getCode();
        result = result * PRIME + ($code == null ? 43 : $code.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Subject(id=" + this.getId() + ", name=" + this.getName() + ", code=" + this.getCode() + ", hoursPerWeek=" + this.getHoursPerWeek() + ", isLab=" + this.isLab() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Subject() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Subject(final Long id, final String name, final String code, final int hoursPerWeek, final boolean isLab) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.hoursPerWeek = hoursPerWeek;
        this.isLab = isLab;
    }
}
