// Generated by delombok at Tue Apr 07 10:25:19 IST 2026
package com.vit.timetable.model;

import jakarta.persistence.*;
import lombok.*;
import java.util.List;

@Entity
@Table(name = "teachers")
public class Teacher {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    private String email;
    // Max teaching hours per week (e.g., 20)
    private int maxHoursPerWeek;
    // Many-to-many: a teacher can teach multiple subjects
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "teacher_subjects", joinColumns = @JoinColumn(name = "teacher_id"), inverseJoinColumns = @JoinColumn(name = "subject_id"))
    private List<Subject> subjects;

    public Long getId() {
        return this.id;
    }

    public List<Subject> getSubjects() {
        return this.subjects;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TeacherBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String email;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int maxHoursPerWeek;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<Subject> subjects;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TeacherBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Teacher.TeacherBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Teacher.TeacherBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Teacher.TeacherBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Teacher.TeacherBuilder maxHoursPerWeek(final int maxHoursPerWeek) {
            this.maxHoursPerWeek = maxHoursPerWeek;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Teacher.TeacherBuilder subjects(final List<Subject> subjects) {
            this.subjects = subjects;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Teacher build() {
            return new Teacher(this.id, this.name, this.email, this.maxHoursPerWeek, this.subjects);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Teacher.TeacherBuilder(id=" + this.id + ", name=" + this.name + ", email=" + this.email + ", maxHoursPerWeek=" + this.maxHoursPerWeek + ", subjects=" + this.subjects + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Teacher.TeacherBuilder builder() {
        return new Teacher.TeacherBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getMaxHoursPerWeek() {
        return this.maxHoursPerWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMaxHoursPerWeek(final int maxHoursPerWeek) {
        this.maxHoursPerWeek = maxHoursPerWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubjects(final List<Subject> subjects) {
        this.subjects = subjects;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Teacher)) return false;
        final Teacher other = (Teacher) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getMaxHoursPerWeek() != other.getMaxHoursPerWeek()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$subjects = this.getSubjects();
        final java.lang.Object other$subjects = other.getSubjects();
        if (this$subjects == null ? other$subjects != null : !this$subjects.equals(other$subjects)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Teacher;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getMaxHoursPerWeek();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $subjects = this.getSubjects();
        result = result * PRIME + ($subjects == null ? 43 : $subjects.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Teacher(id=" + this.getId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", maxHoursPerWeek=" + this.getMaxHoursPerWeek() + ", subjects=" + this.getSubjects() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Teacher() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Teacher(final Long id, final String name, final String email, final int maxHoursPerWeek, final List<Subject> subjects) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.maxHoursPerWeek = maxHoursPerWeek;
        this.subjects = subjects;
    }
}
