// Generated by delombok at Tue Apr 07 10:25:19 IST 2026
package com.vit.timetable.model;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "time_slots")
public class TimeSlot {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // Day of week: MONDAY, TUESDAY, etc.
    @Column(name = "day_of_week")
    private String day;
    // e.g., "09:00"
    private String startTime;
    // e.g., "10:00"
    private String endTime;
    // Period number on that day (1, 2, 3...) — used for gap checking
    private int periodNumber;
    // Is this the lunch slot? (we never schedule here)
    private boolean isLunch;

    public Long getId() {
        return this.id;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TimeSlotBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String day;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String startTime;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String endTime;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int periodNumber;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean isLunch;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TimeSlotBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimeSlot.TimeSlotBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimeSlot.TimeSlotBuilder day(final String day) {
            this.day = day;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimeSlot.TimeSlotBuilder startTime(final String startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimeSlot.TimeSlotBuilder endTime(final String endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimeSlot.TimeSlotBuilder periodNumber(final int periodNumber) {
            this.periodNumber = periodNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimeSlot.TimeSlotBuilder isLunch(final boolean isLunch) {
            this.isLunch = isLunch;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimeSlot build() {
            return new TimeSlot(this.id, this.day, this.startTime, this.endTime, this.periodNumber, this.isLunch);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "TimeSlot.TimeSlotBuilder(id=" + this.id + ", day=" + this.day + ", startTime=" + this.startTime + ", endTime=" + this.endTime + ", periodNumber=" + this.periodNumber + ", isLunch=" + this.isLunch + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static TimeSlot.TimeSlotBuilder builder() {
        return new TimeSlot.TimeSlotBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDay() {
        return this.day;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getPeriodNumber() {
        return this.periodNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isLunch() {
        return this.isLunch;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDay(final String day) {
        this.day = day;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartTime(final String startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndTime(final String endTime) {
        this.endTime = endTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPeriodNumber(final int periodNumber) {
        this.periodNumber = periodNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLunch(final boolean isLunch) {
        this.isLunch = isLunch;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TimeSlot)) return false;
        final TimeSlot other = (TimeSlot) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getPeriodNumber() != other.getPeriodNumber()) return false;
        if (this.isLunch() != other.isLunch()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$day = this.getDay();
        final java.lang.Object other$day = other.getDay();
        if (this$day == null ? other$day != null : !this$day.equals(other$day)) return false;
        final java.lang.Object this$startTime = this.getStartTime();
        final java.lang.Object other$startTime = other.getStartTime();
        if (this$startTime == null ? other$startTime != null : !this$startTime.equals(other$startTime)) return false;
        final java.lang.Object this$endTime = this.getEndTime();
        final java.lang.Object other$endTime = other.getEndTime();
        if (this$endTime == null ? other$endTime != null : !this$endTime.equals(other$endTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TimeSlot;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getPeriodNumber();
        result = result * PRIME + (this.isLunch() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $day = this.getDay();
        result = result * PRIME + ($day == null ? 43 : $day.hashCode());
        final java.lang.Object $startTime = this.getStartTime();
        result = result * PRIME + ($startTime == null ? 43 : $startTime.hashCode());
        final java.lang.Object $endTime = this.getEndTime();
        result = result * PRIME + ($endTime == null ? 43 : $endTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "TimeSlot(id=" + this.getId() + ", day=" + this.getDay() + ", startTime=" + this.getStartTime() + ", endTime=" + this.getEndTime() + ", periodNumber=" + this.getPeriodNumber() + ", isLunch=" + this.isLunch() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TimeSlot() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TimeSlot(final Long id, final String day, final String startTime, final String endTime, final int periodNumber, final boolean isLunch) {
        this.id = id;
        this.day = day;
        this.startTime = startTime;
        this.endTime = endTime;
        this.periodNumber = periodNumber;
        this.isLunch = isLunch;
    }
}
