// Generated by delombok at Tue Apr 07 10:25:19 IST 2026
package com.vit.timetable.model;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "timetable_entries")
public class TimetableEntry {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String division;
    @ManyToOne
    @JoinColumn(name = "subject_id")
    private Subject subject;
    @ManyToOne
    @JoinColumn(name = "teacher_id")
    private Teacher teacher;
    @ManyToOne
    @JoinColumn(name = "room_id")
    private Room room;
    @ManyToOne
    @JoinColumn(name = "timeslot_id")
    private TimeSlot timeSlot;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public Teacher getTeacher() {
        return this.teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public Room getRoom() {
        return this.room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public TimeSlot getTimeSlot() {
        return this.timeSlot;
    }

    public void setTimeSlot(TimeSlot timeSlot) {
        this.timeSlot = timeSlot;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TimetableEntryBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String division;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Subject subject;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Teacher teacher;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Room room;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private TimeSlot timeSlot;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TimetableEntryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimetableEntry.TimetableEntryBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimetableEntry.TimetableEntryBuilder division(final String division) {
            this.division = division;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimetableEntry.TimetableEntryBuilder subject(final Subject subject) {
            this.subject = subject;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimetableEntry.TimetableEntryBuilder teacher(final Teacher teacher) {
            this.teacher = teacher;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimetableEntry.TimetableEntryBuilder room(final Room room) {
            this.room = room;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimetableEntry.TimetableEntryBuilder timeSlot(final TimeSlot timeSlot) {
            this.timeSlot = timeSlot;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TimetableEntry build() {
            return new TimetableEntry(this.id, this.division, this.subject, this.teacher, this.room, this.timeSlot);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "TimetableEntry.TimetableEntryBuilder(id=" + this.id + ", division=" + this.division + ", subject=" + this.subject + ", teacher=" + this.teacher + ", room=" + this.room + ", timeSlot=" + this.timeSlot + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static TimetableEntry.TimetableEntryBuilder builder() {
        return new TimetableEntry.TimetableEntryBuilder();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TimetableEntry)) return false;
        final TimetableEntry other = (TimetableEntry) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$division = this.getDivision();
        final java.lang.Object other$division = other.getDivision();
        if (this$division == null ? other$division != null : !this$division.equals(other$division)) return false;
        final java.lang.Object this$subject = this.getSubject();
        final java.lang.Object other$subject = other.getSubject();
        if (this$subject == null ? other$subject != null : !this$subject.equals(other$subject)) return false;
        final java.lang.Object this$teacher = this.getTeacher();
        final java.lang.Object other$teacher = other.getTeacher();
        if (this$teacher == null ? other$teacher != null : !this$teacher.equals(other$teacher)) return false;
        final java.lang.Object this$room = this.getRoom();
        final java.lang.Object other$room = other.getRoom();
        if (this$room == null ? other$room != null : !this$room.equals(other$room)) return false;
        final java.lang.Object this$timeSlot = this.getTimeSlot();
        final java.lang.Object other$timeSlot = other.getTimeSlot();
        if (this$timeSlot == null ? other$timeSlot != null : !this$timeSlot.equals(other$timeSlot)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TimetableEntry;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $division = this.getDivision();
        result = result * PRIME + ($division == null ? 43 : $division.hashCode());
        final java.lang.Object $subject = this.getSubject();
        result = result * PRIME + ($subject == null ? 43 : $subject.hashCode());
        final java.lang.Object $teacher = this.getTeacher();
        result = result * PRIME + ($teacher == null ? 43 : $teacher.hashCode());
        final java.lang.Object $room = this.getRoom();
        result = result * PRIME + ($room == null ? 43 : $room.hashCode());
        final java.lang.Object $timeSlot = this.getTimeSlot();
        result = result * PRIME + ($timeSlot == null ? 43 : $timeSlot.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "TimetableEntry(id=" + this.getId() + ", division=" + this.getDivision() + ", subject=" + this.getSubject() + ", teacher=" + this.getTeacher() + ", room=" + this.getRoom() + ", timeSlot=" + this.getTimeSlot() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TimetableEntry() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TimetableEntry(final Long id, final String division, final Subject subject, final Teacher teacher, final Room room, final TimeSlot timeSlot) {
        this.id = id;
        this.division = division;
        this.subject = subject;
        this.teacher = teacher;
        this.room = room;
        this.timeSlot = timeSlot;
    }
}
